name: hunter
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.7
  - setuptools=59.5.0
  - pip
  - pytorch::pytorch=1.12.*
  - cudatoolkit=11.3.*
  - openmm=7.5.1
  - pdbfixer
  - hmmer=3.3.2
  - hhsuite=3.3.0
  - kalign2=2.04
  - dssp
  - foldseek
  - seqkit
  - einops=0.6.1
  - fairscale
  - hydra-core
  - omegaconf
  - pandas
  - pytest

  - pip:
      - biopython==1.79
      - fair-esm[esmfold]
      - deepspeed==0.5.9
      - dm-tree==0.1.6
      - ml-collections==0.1.0
      - pytorch-lightning==1.5.10
      - wandb==0.12.21
      - numpy==1.21.2
      - scipy==1.7.1
      - PyYAML==5.4.1
      - requests==2.26.0
      - tqdm==4.62.2
      - typing-extensions==3.10.0.2
      - git+https://github.com/NVIDIA/dllogger.git
      - git+https://github.com/aqlaboratory/openfold.git@4b41059694619831a7db195b7e0988fc4ff3a307