name: hunter
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aria2=1.37.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - dssp=4.5.3
  - foldseek=10.941cd33
  - gawk=5.3.1
  - gmp=6.3.0
  - icu=73.2
  - ld_impl_linux-64=2.45
  - libasprintf=0.25.1
  - libblas=3.11.0
  - libboost=1.86.0
  - libcblas=3.11.0
  - libffi=3.4.6
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgettextpo=0.25.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libiconv=1.18
  - liblapack=3.11.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - mpfr=4.2.1
  - ncurses=6.5
  - numpy=1.21.6
  - openssl=3.6.0
  - pandas=1.3.5
  - pip=24.0
  - python=3.7.12
  - python-dateutil=2.9.0
  - python_abi=3.7
  - pytz=2024.2
  - readline=8.3
  - seqkit=2.12.0
  - setuptools=59.8.0
  - six=1.16.0
  - sqlite=3.51.1
  - tk=8.6.13
  - wheel=0.42.0
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - fair-esm==2.0.0
